---
name: "Setup Bun + Node + deps"
description: |
  Checkout-independent setup: installs Bun, Node, and project dependencies

inputs:
  node-version:
    description: "Node.js version (LTS recommended for CI stability)"
    required: false
    default: "22"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      # Pinned action SHA for supply-chain safety.
      # Tag v2.0.2 -> commit 735343b667d3e6f658f44d0eca948eb6282f2b76
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      with:
        bun-version: 1.3.9

    - name: Setup Node.js
      # Pinned action SHA for supply-chain safety.
      # Tag v4 -> commit 49933ea5288caeca8642d1e84afbd3f7d6820020
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      # Pinned action SHA for supply-chain safety.
      # Tag v4 -> commit 5a3ec84eff668545956fd18022155c47e93e2684
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          node_modules
          ~/.bun/install/cache
        key: >-
          bun-${{ runner.os }}-${{ inputs.node-version }}-
          ${{ hashFiles('bun.lock') }}
        restore-keys: |
          bun-${{ runner.os }}-${{ inputs.node-version }}-
          bun-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
